/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.20
 * Generated at: 2019-06-17 04:37:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Dto.MovieDTO;
import Dao.MovieDAO;
import java.util.ArrayList;

public final class moviechoice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Dao.MovieDAO");
    _jspx_imports_classes.add("Dto.MovieDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>영화 예매</title>\r\n");

	String id = (String) session.getAttribute("id");
	String pw = (String) session.getAttribute("pw");
	MovieDAO movieDAO = new MovieDAO();
	ArrayList<MovieDTO> dtos = movieDAO.LoadMovie();

	request.setCharacterEncoding("UTF-8");
	String m_img = request.getParameter("m_img");
	String theater = request.getParameter("theater");
	String m_No = request.getParameter("m_No");
	String r_Date = request.getParameter("r_Date");
	String r_Time = request.getParameter("r_Time");

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tpadding: 10px 20px;\r\n");
      out.write("\tRadius: 20px;\r\n");
      out.write("\tcolor: #353F48;\r\n");
      out.write("\tbackground-color: #FFE699;\r\n");
      out.write("\tborder: solid 2px #C2722E;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("font {\r\n");
      out.write("\tcolor: #353F48;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table border=1 align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td rowspan=4><a href=\"Main.jsp\"><img src=\"Image\\Logo.png\"\r\n");
      out.write("\t\t\t\t\twidth=\"150px\" height=\"150px\" align=\"center\"></a></img></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t<td colspan=\"2\" height=\"50px\" width = \"600px\"><font size=\"150\"\r\n");
      out.write("\t\t\t\tface=\"Arial Black\">MOVIE</font></td>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t");

				if (id == null && pw == null) {
			
      out.write("\r\n");
      out.write("\t\t\t<td height=\"80px\"  width = \"600px\" colspan=2><b> <a href=\"Login.html\">로그인\r\n");
      out.write("\t\t\t\t</a> | <a href=\"Join.html\">회원가입</a></b></td>\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\t<td height=\"80px\"  width = \"600px\" colspan=2><b> <a href=\"Logout.jsp\">로그아웃\r\n");
      out.write("\t\t\t\t</a> | <a href=\"ModifyForm.do?id=");
      out.print(id);
      out.write("\">회원정보 수정</a></b></td>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t<td bgcolor=\"#FFD966\" width=\"100px\"><a href=\"Movies.do\">영화</a></td>\r\n");
      out.write("\t\t\t<td bgcolor=\"#FFD966\" width=\"100px\"><a href=\"moviechoice.jsp\">예매</a></td>\r\n");
      out.write("\t\t\t<td bgcolor=\"#FFD966\" width=\"100px\"><a href=\"MyPageView.do\">마이페이지</td>\r\n");
      out.write("\t\t\t<td bgcolor=\"#FFD966\" width=\"100px\"><a href=\"list.do?pgNum=1\">자유게시판</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<form action=\"CheckSelect.do\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t<table border=0 align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" width=\"900\" height=\"200\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>영화선택</legend>\r\n");
      out.write("\t\t\t\t\t\t<table border=\"0\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- for문으로 DB에서 불러온 갯수만큼 만들어줘야해 -->\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int i = 0; i < dtos.size(); i++) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><img src=\"");
      out.print(dtos.get(i).getM_img());
      out.write("\" width=\"126px\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"180px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 여기까지 for문에 넣어야해 -->\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									for (int i = 0; i < dtos.size(); i++) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><input type=\"radio\" name=\"m_No\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=");
      out.print(dtos.get(i).getM_no());
      out.write('>');
      out.print(dtos.get(i).getTitle());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td width=\"300\" height=\"50\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>극장선택</legend>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"theater\" style=\"width: 300px\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"suyu\">수유</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"mia\">미아</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hagye\">중계</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Junggye\">하계</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"uijeongbu\">의정부</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ilsan\">일산</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hwajeong\">화정</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"300\" height=\"50\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>날짜선택</legend>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"r_Date\" style=\"width: 300px\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"20190617\">2019년06월17일</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"20190618\">2019년06월18일</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"20190619\">2019년06월19일</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"20190620\">2019년06월20일</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"20190621\">2019년06월21일</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"20190622\">2019년06월22일</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"300\" height=\"50\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>시간선택</legend>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"r_Time\" style=\"width: 300px\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0900\">09:00 ~ 11:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1100\">11:00 ~ 13:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1300\">13:00 ~ 15:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1500\">15:00 ~ 17:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1700\">17:00 ~ 19:00</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1900\">19:00 ~ 21:00</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"좌석선택\">\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
